# Generated by Django 4.0.3 on 2022-04-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default="Won't say who", max_length=30)),
                ('picture', models.ImageField(default='Default value', upload_to='')),
                ('title', models.CharField(max_length=20, verbose_name='Название')),
                ('comment', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Made_Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='No title', max_length=40)),
                ('content', models.TextField(blank=True)),
                ('age', models.IntegerField(default='Default value')),
                ('author', models.CharField(default="Won't say who", max_length=30)),
                ('is_published', models.BooleanField(default=True, verbose_name='Public')),
                ('background_color', models.CharField(default='white', max_length=30)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default="Won't say who", max_length=30)),
                ('title', models.CharField(max_length=20)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('cost', models.IntegerField(verbose_name='Цена')),
                ('image', models.ImageField(default='Default value', upload_to='')),
            ],
            options={
                'verbose_name': 'Produkt',
                'verbose_name_plural': 'Produkti',
            },
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesman', models.CharField(default='Salesman', max_length=20)),
                ('buyer', models.CharField(default='Buyer', max_length=20)),
                ('product', models.CharField(default='Something interesting', max_length=30)),
                ('cost', models.IntegerField()),
                ('number', models.IntegerField()),
            ],
        ),
    ]
